services:
  # Caddy reverse proxy
  caddy:
    image: caddy:2-alpine
    container_name: last-whisper-caddy
    ports:
      - "8008:8008"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  # Backend API service - using GitHub Container Registry
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-coachpo/last-whisper}/last-whisper-backend:latest
    container_name: last-whisper-backend
    expose:
      - "8000"
    environment:
      - TTS_PROVIDER=google
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/google-credentials.json
    volumes:
      - audio_data:/app/audio
      - database_data:/app/data
      - ./keys:/app/keys:ro
    restart: unless-stopped

  # Frontend service - using GitHub Container Registry
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-coachpo/last-whisper}/last-whisper-frontend:latest
    container_name: last-whisper-frontend
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  database_data:
    driver: local
  audio_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  caddy_logs:
    driver: local
