services:
  # Caddy reverse proxy
  caddy:
    image: caddy:2-alpine
    container_name: last-whisper-caddy
    ports:
      - "8008:8008"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  # Backend API service - development build
  backend:
    build:
      context: ../last-whisper-backend
      dockerfile: Dockerfile
    container_name: last-whisper-backend-dev
    expose:
      - "8000"
    environment:
      - TTS_PROVIDER=google
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/google-credentials.json
    volumes:
      - audio_data:/app/audio
      - database_data:/app/data
      - ./keys:/app/keys:ro
    restart: unless-stopped

  # Frontend service - development build
  frontend:
    build:
      context: ../last-whisper-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
        - NEXT_PUBLIC_DEBUG_LOGGING=true
        - NODE_ENV=production
        - PORT=3000
        - HOSTNAME=0.0.0.0
    container_name: last-whisper-frontend-dev
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  database_data:
    driver: local
  audio_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  caddy_logs:
    driver: local
