name: Last Whisper Test Pipeline

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [backend, frontend]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive   # Fetch submodules recursively
        fetch-depth: 1          # only fetches the latest commit (shallow clone).
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Docker build
      uses: docker/build-push-action@v5
      with:
        context: ./last-whisper-${{ matrix.service }}
        file: ./last-whisper-${{ matrix.service }}/Dockerfile
        push: false
        load: true
        tags: test-${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/arm64
        build-args: ${{ matrix.service == 'frontend' && 'NEXT_PUBLIC_API_URL=https://lw.687786.xyz/apis
          NEXT_PUBLIC_DEBUG_LOGGING=false
          NODE_ENV=production
          PORT=3000
          HOSTNAME=0.0.0.0' || '' }}
