name: Test Docker Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'last-whisper-backend/**'
      - 'last-whisper-frontend/**'
      - 'last-whisper-backend/Dockerfile'
      - 'last-whisper-frontend/Dockerfile'
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [backend, frontend]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Docker build
      uses: docker/build-push-action@v5
      with:
        context: ./last-whisper-${{ matrix.service }}
        file: ./last-whisper-${{ matrix.service }}/Dockerfile
        push: false
        tags: test-${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

    - name: Test image runs
      run: |
        docker run --rm -d --name test-${{ matrix.service }} test-${{ matrix.service }}:latest
        sleep 10
        docker logs test-${{ matrix.service }}
        docker stop test-${{ matrix.service }}
