name: Test Pipeline

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'last-whisper-backend/**'
      - 'last-whisper-frontend/**'
      - 'last-whisper-backend/Dockerfile'
      - 'last-whisper-frontend/Dockerfile'
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [backend, frontend]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive   # Fetch submodules recursively
        fetch-depth: 1          # only fetches the latest commit (shallow clone).
        token: ${{ secrets.PAT_TOKEN }}

    - name: Debug directory structure
      run: |
        echo "=== Root directory contents ==="
        ls -la
        echo "=== Backend Dockerfile ==="
        ls -la Dockerfile.backend || echo "Backend Dockerfile not found"
        echo "=== Frontend Dockerfile ==="
        ls -la Dockerfile.frontend || echo "Frontend Dockerfile not found"
        echo "=== Backend directory contents ==="
        ls -la last-whisper-backend/ || echo "Backend directory not found"
        echo "=== Frontend directory contents ==="
        ls -la last-whisper-frontend/ || echo "Frontend directory not found"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Docker build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.${{ matrix.service }}
        push: false
        load: true
        tags: test-${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ matrix.service == 'frontend' && 'NEXT_PUBLIC_API_URL=https://lw.687786.xyz/apis
          NEXT_PUBLIC_DEBUG_LOGGING=false
          NODE_ENV=production
          PORT=3000
          HOSTNAME=0.0.0.0' || '' }}

    - name: Test image runs
      run: |
        docker run --rm -d --name test-${{ matrix.service }} test-${{ matrix.service }}:latest
        sleep 10
        docker logs test-${{ matrix.service }}
        docker stop test-${{ matrix.service }}
